#!/usr/bin/env perl
use Cwd;
my $dir = "tmp_circularised";

my @circlator_output_files         = ("00.info.txt",
									  "00.input_assembly.fasta",
									  "00.input_assembly.fasta.fai",
									  "01.mapreads.bam",
									  "01.mapreads.bam.bai",
									  "02.bam2reads.log",
									  "02.bam2reads.fasta",
									  "04.merge.coords",
									  "04.merge.fasta",
									  "04.merge.merge.iterations.log",
									  "04.merge.merge.log",
									  "04.merge.circularise_details.log",
									  "04.merge.circularise.log",
									  "04.merge.merge.iter.1.reads.log",
									  "04.merge.merge.iter.2.reads.log",
									  "04.merge.merge.iter.10.reads.log",
									  "05.clean.contigs_to_keep",
									  "05.clean.log",
									  "05.clean.coords",
									  "05.clean.fasta",
									  "05.clean.remove_small.fa",
									  "06.fixstart.fasta",
									  "06.fixstart.contigs_to_not_change",
									  "06.fixstart.log",
									  "06.fixstart.fasta",
									  "06.fixstart.ALL_FINISHED",
									  );
									  
my @circlator_output_dir			= ("03.assemble");

my $cwd = getcwd();
system("mkdir $dir");
chdir ("$dir");
system("touch ".join(" ", @circlator_output_files));
system("mkdir ".join(" ", @circlator_output_dir));

# test logs
system("echo log_1 > 02.bam2reads.log");
system("echo log_2 > 04.merge.merge.iter.1.reads.log");
system("echo log_3 > 04.merge.merge.iter.2.reads.log");
system("echo log_4 > 04.merge.merge.iter.10.reads.log");
system("echo log_5 > 04.merge.merge.iterations.log");
system("echo log_6 > 04.merge.merge.log");
system("echo log_7 > 04.merge.circularise_details.log");
system("echo log_8 > 04.merge.circularise.log");
system("echo log_9 > 05.clean.log");
system("echo log_10 > 06.fixstart.log");

chdir $cwd;




